/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuerdoRouteImport } from './routes/recuerdo'
import { Route as IndexRouteImport } from './routes/index'

const RecuerdoRoute = RecuerdoRouteImport.update({
  id: '/recuerdo',
  path: '/recuerdo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recuerdo': typeof RecuerdoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recuerdo': typeof RecuerdoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recuerdo': typeof RecuerdoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recuerdo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recuerdo'
  id: '__root__' | '/' | '/recuerdo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecuerdoRoute: typeof RecuerdoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuerdo': {
      id: '/recuerdo'
      path: '/recuerdo'
      fullPath: '/recuerdo'
      preLoaderRoute: typeof RecuerdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecuerdoRoute: RecuerdoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
